### PR TITLE
Just define a label for the fieldset

### PR DESCRIPTION
**Pull request by photodude**
The OS training example this comes from was overly complicated in it's label code. It's simpler to just define a label for the fieldset in the XML and echo that value (as is done for each field).

### CODE REVIEW

**Comment by thg303** [comment]
well that's simpler to write, but my friend, in case of supporting multilanguage form, we have no other choice, we have to use that "JText::_(...)" function.

**Comment by photodude** [comment]
@thg303 In case of supporting multilanguage forms, the form fieldset labels just need to be a language string in all caps and defined in the language files. So that you would end up with something like `COM_EXAMPLE_MYFIELDSET_LABEL` for your label language string, and the definition of `COM_EXAMPLE_MYFIELDSET_LABEL` language string in the language files. There is no need to use the `JText::_(...)` function. JForm and core Joomla should handle the supporting of multilanguage forms when constructed in this manor with language strings.

The whole example should get some language string refactoring as all of the labels are improperly defined using `MY TEXT FIELD LABEL` rather than proper `COM_AQJFORM_MY_TEXT_FIELD_LABEL` language strings.

**Comment by photodude** [comment]
@thg303 I've added some basic Language Strings to the example for multilanguage support options.

**Comment by photodude** [comment]
@thg303 I'm closing this, but you really should use basic Language Strings example for multilanguage support options especially with J3.7.

**Pull request closed without merging**
